### ISSUE TITLE
ValliStart displays as windows starts .

### ISSUE THREAD

**Issue by PhoenixCODE2322** [Jax-Core/ValliStart#11]
it automatically displays the start menu when i log into windows. i have rainmeter portable set to start as i log in using task scheduler.

because of this rainmeter hangs and other software are trying to boot up at this time.. is there a way for it to not show up when i log into windows. i am on latest Jax core and Vallistart. i read other issue where other user had same issue but he went afk. so i am providing this in advance.

Vars.inc
`[Variables]
ReplaceWin =1
Mode =1
2412 = H
StartText =Welcome back!
IconName =Core

Font = Segoe UI
Scale =0.78
Corner = 1
Stroke =0
Edge =15

Player =NP
NPName =CAD
FetchImage =0

Location =Custom
ShowSec =1
Animated = 1
TypeToSearch =0
Blur =None

Module1 =Music
Module2 =Connection
Module3 =Resource

Monitor = 1

Accent =242, 52, 0
Alpha =255
Color =12,12,12
Border =28,28,28
FontColor =242,240,255
DarkColor =120,120,120
BoxBorder =35,35,35
BoxColor =35,35,35

WeatherLocation = Hong Kong
WeatherUnits = Metric
Language = en

;;╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
;;║ METERSTYLES                                                                                          ║
;;╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝

[BoldText]
FontFace = #Font#
FontWeight = 800
AntiAlias = 1
FontColor = #FontColor#
FontSize = (11*#Scale#)
SolidColor = 0,0,0,1

[SemiBoldText]
FontFace = #Font#
FontWeight = 500
AntiAlias = 1
FontColor = #FontColor#
FontSize = (11*#Scale#)
SolidColor = 0,0,0,1

[RegularText]
FontFace = #Font#
AntiAlias = 1
FontColor = #FontColor#
FontSize = (11*#Scale#)
SolidColor = 0,0,0,1
`

**Comment by EnhancedJax** [comment]
This issue will be fixed for the coming 3.0 update. You can add `[!Hide]` in front of `onrefreshaction` in `Vallistart\Main\Main.ini`
