### ISSUE TITLE
ValliStart Rejecets every Mouse Click

### ISSUE THREAD

**Issue by Akorian** [Jax-Core/ValliStart#16]
When using ValliStart even when it's not open, I find myself sometimes unable to left-click anything. When I right-click I get the Rainmeter Context Menu for ValliStart where I can choose to unload it. 

I am running up to date Windows 10 with no other Rainmeter skins apart from yourVolumeMixer on a Dell Precision 5550.

**Comment by EnhancedJax** [comment]
Seems like a legacy issue, can you try reinstalling the module?
