### ISSUE TITLE
Rounded corner issue with acrylic/blur background

### ISSUE THREAD

**Issue by firegirl123** [Jax-Core/ValliStart#18]
When the background of the start menu is set to acrylic or blur, there's shadows of sharp corners ghosting behind the rounded ones: 
![corner](https://user-images.githubusercontent.com/99143964/156864276-77a1e4b4-047f-4f07-98f5-dcaf906d98e8.png)
It's more noticeable against a dark background:
![corner 2](https://user-images.githubusercontent.com/99143964/156864318-c1ffef84-a1a6-4af9-85f6-94f856685e67.png)

Is there a solution for this while still keeping it acrylic?

**Comment by EnhancedJax** [comment]
If you're on windows 10, no. Windows doesn't have the correct components to have that effect. For windows 11 however you can choose the rounding corner. It is noted that for some users they still can't have the rounding effect, and this will be fixed asap,
