### ISSUE TITLE
Weather could use a margin with the music widget

### ISSUE THREAD

**Issue by auctumnus** [Jax-Core/ValliStart#19]
Love this entire project! My only gripe is that the weather widget looks kinda weird with the sidebar theme:

![image](https://user-images.githubusercontent.com/37276280/157176999-6e568583-e8eb-4361-88aa-2efffd7dae65.png)

It could probably use a bit more space between the two? I would just use the veklMusic widget but I think it's really cute to be able to like the currently playing song from the widget.

**Comment by EnhancedJax** [comment]
The two sets don't really work well together, I suppose I can add an option to add some padding for the default music widget. I'll add this after my break, thanks for the suggestion!
