### ISSUE TITLE
Does ValliStart have the ability to create start menu folders or similar?

### ISSUE THREAD

**Issue by NotIkitClaw** [Jax-Core/ValliStart#21]
What I mean by "start menu folders" are like an organised bundle of other files or whatever on the start menu. This screenshot of upcoming feature to create start menu folders in Windows 11 is what I mean https://cdn.vox-cdn.com/thumbor/oESgqAFn3LztRDnEJykzRQt5IaM=/0x0:1129x759/1200x800/filters:focal(475x290:655x470)/cdn.vox-cdn.com/uploads/chorus_image/image/70517612/Start_Folders.0.png

**Comment by EnhancedJax** [comment]
not as of now
