### ISSUE TITLE
[Feature Request] Search Within Vallistart (To improve immersion)

### ISSUE THREAD

**Issue by Brickmaster1** [Jax-Core/ValliStart#22]
Is there any way to get a custom search that is within the vallistart start menu, because I don't like having to use the windows search to search things instead of the vallistart menu which would just feel like it had so much more integration.

**Comment by EnhancedJax** [comment]
Sorry, this isn't possible right now, though you can use any 3rd party keystroke launcher like power toys run to work with vallistart

**Comment by Brickmaster1** [comment]
How would this work, like how would I set it up? Also, how do I make your keystroke launcher open programs and stuff, the menu was very confusing to me.

**Comment by EnhancedJax** [comment]
No, my keystrokes module is not a keystrokes launcher. A keystrokes launcher is something like power toys which you use to launch apps. Just set the search hotkey to run in general settings to the launchers'

**Comment by Brickmaster1** [comment]
Is there any way to make a keystroke send another key to the system

**Comment by EnhancedJax** [comment]
What?

**Comment by Brickmaster1** [comment]
Like, press Ctrl + Alt + W it presses it sends Win as well for example

**Comment by EnhancedJax** [comment]
That isn't something you do with this? All you have to do to use a third party launcher with vallistart is to change the hotkey it activates when searching to the one you use to activate that 3rd party launcher

**Comment by Brickmaster1** [comment]
I know but I also use other programs I would use this with and I was just wondering if you knew a way that it would be possible

**Comment by Brickmaster1** [comment]
I mean I know of an app called phrase express
