### ISSUE TITLE
Can't download/update.

### ISSUE THREAD

**Issue by zaxiify** [Jax-Core/ValliStart#23]
Whenever I try to redownload/update ValliStart, it just throws an error message saying either "Unable to move to: C:\Users\myname\Documents\Rainmeter\Skins\@Backup\ValliStart" or " Unable to create file: C:\Users\myname\Documents\Rainmeter\Skins\ValliStart\@Resources\Actions\AHKv1.exe. Skin Installer will now quit. Click OK to close Skin Installer." (when I turn backup skin off in installer)

**Comment by EnhancedJax** [comment]
Turn skin off first then update, or use core to update vallistart
