### ISSUE TITLE
Configuration doesnt save

### ISSUE THREAD

**Issue by willral** [Jax-Core/ValliStart#24]
whenever I turn on my pc, settings for ValliStart (3.? recently updated to 3.4 but It doesnt state last version most likely 3.3) have reverted back to old settings.

- The position changes from bottom left to top right
- The y padding size changes
- The activation mode changes from Replace start back to separate module

using windows 10, other installed programs:
droptop, ModularClocks (2.23), ModularPlayers (2.42)

**Comment by willral** [comment]
Is happening on 3.4 too

**Comment by EnhancedJax** [comment]
Are you on the latest version of core?

**Comment by willral** [comment]
v44905

**Comment by EnhancedJax** [comment]
Do you have droptop installed? Turn access droptop from any app off

**Comment by willral** [comment]
as stated In my original post I do.
how do I find this setting?
