### ISSUE TITLE
Vallistart bugging when I use the "Win" Key

### ISSUE THREAD

**Issue by ItzRainbowMC** [Jax-Core/ValliStart#28]
whenever i use the windows key to open Vallistart, it bugs.
meanwhile, when I use droptop's win key, it bugs a bit then fixes itself.
I'm on the latest version on win10.

**Comment by EnhancedJax** [comment]
Close all ahk process from Vallistart's info settings, then activate again. Make sure you are on the latest version of Droptop. FYI, JaxCore is not part of Droptop, so if you have any questions regarding Droptop, consider asking on their Discord server.

**Comment by PurelyStupidity** [comment]
This seems to happen everytime my computer launches

**Comment by EnhancedJax** [comment]
Try the fix above

**Comment by PurelyStupidity** [comment]
I have to do the fix every time my computer launches

**Comment by EnhancedJax** [comment]
Make sure both ValliStart and Droptop is up to date, and re-integrate ValliStart to Droptop.
