### ISSUE TITLE
[Feature request] Secondary level of pinned applications / folders

### ISSUE THREAD

**Issue by Timmiej93** [Jax-Core/ValliStart#29]
A few remarks before I begin:
- I know this isn't an issue, but there doesn't seem to be any other way to contact the dev (other than Discord, which is a horrible place for discussion and idea sharing compared to a regular forum)
- I'm new to ValliStart, so there's a chance this is already an option and I'm just not aware of it.

So in Win10, I used the start menu as (I think) it should be used. I had it full-screen, mainly because the dumb tiles were so big, but it was completely structured to my liking. A group of tiles here, a group of tiles there, all neatly packed and with great overview. Win11 took this away, since you can only have apps in concurrent fashion, all in a line. ValliStart does kinda provide this option, but there currently simply isn't enough room to pin apps, with a maximum of 10. That's why I have a proposal.

I would love to see an option to convert a "box" to a clickthrough / folder, like you have on smartphones. Basically, you click a box, and it either opens a new overlay, or it converts the current overlay to the new one, maybe something like this (excuse my awesome paint skills, it's only to get the point across)
<img src="https://user-images.githubusercontent.com/16491748/176685118-17f4c754-1da2-49a3-a3f5-0a4de566a424.png" width="300px"/>

As you can see, this would allow us to have 30 pinned apps per folder, allowing for a total of 300 pinned apps by "just" adding a layer, and scrolling could even be added. 

As a secondary suggestion: It would also be nice if a wider start menu would result in more "boxes", instead of them becoming larger, or if there was an option to set the number of boxes per row, to make it even more customizable. To finish off: it would be nice if empty boxes could be "invisible", so it's really possible to make a nice grouping of your apps.

Other than that, I feel like this is the first start menu alternative that's actually worth using, so great job! Hopefully it'll continue to improve over time.

**Comment by EnhancedJax** [comment]
Thank you for a great and detailed suggestion! I am aware of how limited ValliStart's current shortcut system is, hence ValliStart's coming major update is to improve the shortcuts! I'll try to add folders and dynamic shortcut count in that update.

**Comment by EnhancedJax** [comment]
Added in v3.5
