### ISSUE TITLE
ValliStart not reopening properly after clicking on desktop

### ISSUE THREAD

**Issue by Djastin04** [Jax-Core/ValliStart#33]
After clicking anywhere on ValliStart and then clicking on the desktop, the ValliStart/Winblock replacement widget disappears and only reappears after clicking on a different Rainmeter widget or the taskbar.
Otherwise, Vallistart still opens, if done so through the Windows key, but won't do it through the replacement start button/widget given that it disappeared.

**Comment by EnhancedJax** [comment]
Make sure Winblock has stay topmost options set correctly.

**Comment by Djastin04** [comment]
Thank you for responding, I already checked beforehand if that was the problem and it was already set to stay topmost.

**Comment by EnhancedJax** [comment]
Do you happen to have wallpaper engine? Winblock hides itself when a Fullscreen window is focused.

**Comment by Djastin04** [comment]
Yes, I do use wallpaper engine, but this problem still persists even after I close wallpaper engine.
