### ISSUE TITLE
Can't install ValliStart v.3.51 or any version as of last JaxCore update.

### ISSUE THREAD

**Issue by ItsFireStorm** [Jax-Core/ValliStart#35]
So as soon as I updated JaxCore to it's latest version as of now (v.50200) it seemed like ValliStart has been dropping me issues with the following error message:

Script file not found:
C:\Users\\{User}\Documents\Rainmeter\ValliStart\@Resources\Actions\Source Code\Close.ahk (or some other related .ahk warnings)

I've tried re-downloading, downgrading, closing all ahk processes... but nothing seemed to really work.

**Comment by ItsFireStorm** [comment]
Another thing is that I can't get ValliStart to open even if it's not installed, if I hit the Win key it gives me the same error.

**Comment by EnhancedJax** [comment]
Try restarting your device, and reinstall Vallistart again
