### ISSUE TITLE
i can't open The "JaxCore Config Hub"

### ISSUE THREAD

**Issue by goodhacker-art** [Jax-Core/ValliStart#36]
https://user-images.githubusercontent.com/72574332/182008884-84438305-bfdb-4f78-b1b7-637c7a687e86.mp4

**Comment by goodhacker-art** [comment]
I apologize if this issue is irrelevant to
ValliStart

**Comment by EnhancedJax** [comment]
1. Go to the Rainmeter Manage panel (found in your app tray) and set `#JaxCore\main` coordinates to `0 0`
2. Deactivate and activate it
3. After that, Re-create JaxCore's shortcut in it's setting page so that this issue never happens again

**Comment by Adalind-no-commit-git** [comment]
i cant find `#JaxCore\main` in the rainmeter manage panel

**Comment by EnhancedJax** [comment]
![image](https://user-images.githubusercontent.com/80020581/183007435-5b384fe4-7dfc-4d36-ae4b-f098a3ff5cd0.png)
![image](https://user-images.githubusercontent.com/80020581/183007451-118f96bd-9646-4549-82bd-aa04c1cf357f.png)
