### ISSUE TITLE
Area (not only module) under Vallistart media player line goes transparent when switching videos with Auto Resize.

### ISSUE THREAD

**Issue by Aegim** [Jax-Core/ValliStart#40]
When switching to another video, the area under the media player's line will become transparent. The transparency goes past the module and dividing lines. When set to acrylic, the area beneath becomes standard transparency. When trying to switch to Dark and CoreUI I experienced the area beneath having an opacity of nearly 0%. Sometimes it goes away, but that has only happened a few times. It may be an issue with auto resize kicking in before the video player does, but I cannot say for sure. I haven't found a way to disable it after enabling other than what is mentioned next. The issue seemed to go away after uninstalling and reinstalling, but auto resize was the main difference before I did that. Though, it returned shortly after. Refreshing is a momentary fix as it returns after as well and I end up entering and exiting to re-enable Bluetooth since it gets turned off. I also experience Vallistart freezing when clicking "Reconfigure in Core" and have to click on the start orb to exit out instead of clicking on a separate area of the screen. It stays frozen above all my windows. Rainmeter had suddenly closed and when I returned, the basic Win11 start menu appeared instead of the sidebar. I apologize as I am unable to contribute much to this matter other than report my issues since I am getting into coding. Sorry for any confusion my explanations may bring. Have a nice day!

Best regards

**Comment by Aegim** [comment]
I apologize as I had failed to notice that the guide in General could solve my third issue, but you brought it to my attention. Thank you so much for the help you've provided and the effort put into your work!

**Comment by EnhancedJax** [comment]
> When switching to another video, the area under the media player's line will become transparent. The transparency goes past the module and dividing lines. When set to acrylic, the area beneath becomes standard transparency. When trying to switch to Dark and CoreUI I experienced the area beneath having an opacity of nearly 0%. Sometimes it goes away, but that has only happened a few times. 

I am unable to produce this issue (it should be fixed in a few updates earlier), do you think you can attach a screenshot / video?

**Comment by Aegim** [comment]
![image](https://user-images.githubusercontent.com/111807698/186374433-3c619656-0fa4-4ab0-b181-8f69619ceab1.png)
![image](https://user-images.githubusercontent.com/111807698/186374725-4dfe0046-ce6e-434c-b7d2-fc0ad3c59261.png)

**Comment by Aegim** [comment]
(Some more screenshots since the first two were about a minute apart): 
![Screenshot (3787)](https://user-images.githubusercontent.com/111807698/186380063-46cb8426-d8f5-433a-9389-05f17354ba7d.png)
![Screenshot (3788)](https://user-images.githubusercontent.com/111807698/186380068-f098292f-977c-403f-8935-6257f063a4ad.png)

**Comment by Aegim** [comment]
If a blur type other than "None" is set on an opaque color scheme, there appears to be a border above the frosty area when the issue occurs (Noticeable with Dracula and Nord). Standard causes the area to become frosty and almost clear, while acrylic causes what is shown in the earlier screenshots. When the media player disappears between a video, the modules shift up and the remaining opaque space stays. The empty, but still opaque space disappears, then the media player pushes Hot Apps down which may explain the abnormal border and frosty area since Hot Apps should fit, but has shifted down. 
Refreshing momentarily solved it, but it later returns. The issue will return in the middle of viewing videos later. It doesn't always occur right after, but has the chance to happen after one or two videos when the media player tries to load in. Again, requiring a refresh once more. Bluetooth is turned off like in the connection module's preview in Core when refreshing. Clicking the assigned key(s) after will make the sidebar reload, turn Bluetooth back on, and then on the next press will disappear like it normally would. The "Configure in Core" bug causes the area behind the blurred Vallistart menu to show what you were doing behind it prior to opening Core if some form of blur (including the issue) is enabled. Pressing anything related to Vallistart and clicking out causes my pointer to click after my click. I am unsure whether this is a user error or not, nor do I know if games detect it as cheating. I can provide further screenshotting and explaining if need be.
![image](https://user-images.githubusercontent.com/111807698/186386587-95939656-7cad-4214-9b14-e1b3aa3ae9cd.png)
![image](https://user-images.githubusercontent.com/111807698/186386743-2052a4ef-d285-4107-b112-86bf2d3bc5f1.png)

**Comment by Aegim** [comment]
(Screenshots of media player loading in and out):

![Screenshot (3805)](https://user-images.githubusercontent.com/111807698/186399889-90cab519-94ce-4115-971a-36440c6235cc.png)
![Screenshot (3806)](https://user-images.githubusercontent.com/111807698/186399895-8b96ba4b-d5ec-4b18-9a41-00bd7f180466.png)

**Comment by Aegim** [comment]
(Outside of media playing, a space large enough for the media player is shown (Auto-Resizing is currently disabled (will test))):
![image](https://user-images.githubusercontent.com/111807698/186401434-c5b34fab-97d5-48bd-aae0-dba1a0e5db20.png)

**Comment by EnhancedJax** [comment]
Fixed in v3.55, thank you!

**Comment by Aegim** [comment]
I should be the one to thank you for fixing this issue!
