### ISSUE TITLE
Vallistart "Corner Rounding Exception List" settings are now #RemoveRoundCorner# which doesn't remove the corners (normal settings still do)

### ISSUE THREAD

**Issue by Aegim** [Jax-Core/ValliStart#41]
Simply typing 1111 in Ver. 3.54 would set the corners to a right angle even without the vertical bars, but do not anymore. Originally, there would be a setting of 0|0|0|0 that you could change to 1|1|1|1, making the corners right angled. When clicking into the box there appear to be brackets that make it look like [#RemoveRoundCorner#]. The issue is that it doesn't seem to remove round corners. Blur rounding size is currently set to "None" so this may be another issue, or perhaps it's just my own. 
![image](https://user-images.githubusercontent.com/111807698/186495307-0cb8bd5c-cccc-4559-b312-e41d00738136.png)
![image](https://user-images.githubusercontent.com/111807698/186495258-bd849267-8c85-4d84-9717-83db38dd737b.png)
![image](https://user-images.githubusercontent.com/111807698/186495148-84fa71d6-074f-4f56-8daf-5f5ac7699ebe.png)
![image](https://user-images.githubusercontent.com/111807698/186495830-b6cd20a5-6ae6-4238-a022-55a6e23a9ef7.png)
![image](https://user-images.githubusercontent.com/111807698/186495890-93dc9562-f16c-4d6e-b064-840a2daf5de0.png)

**Comment by EnhancedJax** [comment]
I've removed that option as it does not work well with blur. You should change the Corner roundness instead. The visual bug has been updated in 3.56, thanks!
