### ISSUE TITLE
When YourFlyouts is enabled, Vallistart's media player is hidden until refreshed when playing media

### ISSUE THREAD

**Issue by Aegim** [Jax-Core/ValliStart#43]
It is understandable to assume that one or the other is all that is needed, but is there a way to ensure that both are enabled from startup? Refreshing Vallistart and pressing an assigned key(s) twice to exit out of it isn't much of an ordeal. It's become a routine when turning on Windows so I was wondering if this was intentional or a bug since I still open Vallistart to check the volume, track, as well as time. There's another issue I'm experiencing which is the pseudo and power buttons closing and reopening when clicked. If I accidentally click on a button I'd normally click on it again to close it, but these two just reopen. 

Best regards

**Comment by EnhancedJax** [comment]
Might be a problem with the underlying media plugin. There will be an update later on for the plugin which might fix this issue, so I'll hold on until then.

For the other issue, if the button is clicked to an extended period, it would reopen the menu, no way to get around this until we use another method to detect start menu startup.
