### ISSUE TITLE
Can't type at search bar

### ISSUE THREAD

**Issue by keremerbasi** [Jax-Core/ValliStart#44]
tried restarting ctfmon nothing works.
Default taskbar works fine.

**Comment by EnhancedJax** [comment]
You can't type in which searchbar? Can you give more details?

**Comment by keremerbasi** [comment]
> 
![cant3](https://user-images.githubusercontent.com/74865601/188284572-9929647e-e4ad-4da4-a49e-686e88fe33e8.png)

**Comment by EnhancedJax** [comment]
It should launch the default search menu. This should be mentioned in the welcome guide 😃

**Comment by keremerbasi** [comment]
it doesnt launch it thats the problem

Jax ***@***.***>, 4 Eyl 2022 Paz, 08:03 tarihinde şunu yazdı:

**Comment by EnhancedJax** [comment]
Does `Win + S` do anything for you by default? If not then change it to a hotkey that launches your desired search program, if it does work, then try changing `JaxCore -> ValliStart -> General -> Setting: Key to run after key input is captured`

**Comment by keremerbasi** [comment]
shortcut was the problem thanks.
