### ISSUE TITLE
Shortcut keys not working

### ISSUE THREAD

**Issue by Letimaki** [Jax-Core/ValliStart#47]
Shortcut keys do not work with ValliStart if Rainmeter wasn't installed in C:\Program Files\Rainmeter\Rainmeter.exe

**Error message:** 
Error: Failed attempt to launch program or document:
Action: <C:\Program Files\Rainmeter\Rainmeter.exe>
Params: <[!UpdateMeasure mToggle ValliStart\Main]

Specifically: The system cannot find the file specified

**Comment by EnhancedJax** [comment]
Try reinstalling and see if it works

**Comment by EnhancedJax** [comment]
Update to latest JaxCore, and use the debug options to "rollback" to latest version of ValliStart / reinstall ValliStart.
