### ISSUE TITLE
Vallistart uses above 25% CPU

### ISSUE THREAD

**Issue by erkgtn** [Jax-Core/ValliStart#62]
Hi, new to rainmeter here. I've noticed that the cpu usage of rainmeter using Vallistart jumps stable over 25% as soon as "Main/Accessories/Main.ini" is active. I've tried lowering the update under 1000 but usage did not get affected much, just stabilized around 18%. Tried updating powershell with no avail and now I'm asking if anyone has any theories for resolving this issue. 
![Screenshot 2024-01-04 120432](https://github.com/Jax-Core/ValliStart/assets/107864894/1455aa5d-5033-43f5-a77e-4e35021bb26c)

**Comment by erixwd** [comment]
I figured it out. The "resource" module was running in the background constantly loading the cpu for it's readings. I turned it off in the JaxCore "modules" panel and now runs on about 1.2%.

**Comment by erkgtn** [comment]
I figured it out. The "**resource**" module was running in the background constantly loading the cpu for it's readings.
I turned it off in the JaxCore "modules" panel and now runs on about 1.2%.
