### ISSUE TITLE
Unable to create file while installing ValliStart.

### ISSUE THREAD

**Issue by iDCoded** [Jax-Core/ValliStart#8]
When I first downloaded **ValliStart**, it worked perfectly. 

But when I restarted my computer, everything worked perfectly other than **ValliStart*.

I tried reinstalling it but when I did so, I got this error ⬇️ 
![error](https://user-images.githubusercontent.com/65074550/147529693-37ff2d6b-a658-4b71-b64e-91f9fde18973.png)

**Comment by EnhancedJax** [comment]
If you're reinstalling it, make sure the skin is closed before doing so. But since you've done that, close the ahk process from task manager and reinstall it.

**Comment by iDCoded** [comment]
> If you're reinstalling it, make sure the skin is closed before doing so. But since you've done that, close the ahk process from task manager and reinstall it.

I'll give it a try. Thanks.
