### ISSUE TITLE
Getting ValliStart.ahk error 

### ISSUE THREAD

**Issue by PhoenixCODE2322** [Jax-Core/ValliStart#9]
`---------------------------
ValliStart.ahk
---------------------------
Error:  Failed attempt to launch program or document:
Action: <C:\Program Files\Rainmeter\Rainmeter.exe >
Params: <!UpdateMeasure "mToggle" "ValliStart\Main" ">

Specifically: The system cannot find the file specified.

	Line#
	011: }
	012: Else
	013: {
	014: Hotkey,$LWin,Button
	015: Hotkey,LWin & F1,DisabledWin
	016: Return
	017: }
--->	020: Run,"%RainmeterPath% "!UpdateMeasure "mToggle" "ValliStart\Main" "
	021: Return
	024: MsgBox,Windows key + F1
	025: Return
	026: Exit
	027: Exit
	027: Exit

The current thread will exit.
---------------------------
OK   
---------------------------
`

i have portable version of rainmeter. what to do

**Comment by PhoenixCODE2322** [comment]
for the moment i manually changed the %RainmeterPath% to the direct path of my rainmeter in .ahk

**Comment by EnhancedJax** [comment]
Fixed this bug in core 40002, so next time you update it should be
conserved.
